name: niimbot_print_example
description: Demonstrates how to use the niimbot_print plugin.
publish_to: 'none'

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  niimbot_print:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
